name: Generate Snake

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Typing
        uses: Platane/snk@v3
        with:
          github_user_name: ashkant4
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          messages: |
            Thanks
            Welcome to my GitHub!
            ðŸš€ Coding & Learning
            ðŸ’¡ Always improving
            Front-End Developer
            Keep scrolling...
            
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}